# Generated by Django 4.2 on 2023-05-18 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_cart_total'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Size',
            new_name='SizeVariant',
        ),
        migrations.RenameField(
            model_name='cartproduct',
            old_name='size',
            new_name='size_variant',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sizes',
            new_name='size_variant',
        ),
        migrations.RenameField(
            model_name='sizevariant',
            old_name='size',
            new_name='size_name',
        ),
    ]
