# Generated by Django 4.1.6 on 2023-10-07 14:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_product_size_variant_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='phone number should exactly be in 10 digits', regex='^98\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='phone number should exactly be in 10 digits', regex='^98\\d{8}$')]),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
