# Generated by Django 4.2 on 2023-05-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_cartproduct_quantity_remove_cartproduct_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='rate',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='subtotal',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
