# Generated by Django 4.2 on 2023-05-20 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_cartproduct_quantity_cartproduct_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.customer'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='subtotal',
            field=models.PositiveIntegerField(),
        ),
    ]
