# Generated by Django 4.1.6 on 2023-10-08 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_customer_contact_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size_variant',
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='phone number should exactly be in 10 digits and starts with 98', regex='^98\\d{8}$')]),
        ),
    ]
