# Generated by Django 4.2 on 2023-05-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_customer_created_date_customer_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
